name: 08-03-Contexts - Variables

on:

  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Use Workflow Input
        run: |
          echo "DEBUG: ${{ vars.debug }}"
